name: Publish Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with v (e.g., v1.0.0, v2.1.0)

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compress App Bundle
        run: ditto -c -k --keepParent PhotoPrint.app PhotoPrint.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: PhotoPrint.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
